#! /bin/sh
#
# netvird       Start/Stop netvird
start() {
        su -c "/usr/local/bin/netvirt-agent &"
}

stop() {
        su -c "pkill netvirt-agent"
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop 
        sleep 2
        start
        ;;
  *)
        echo $"usage: $0 {start|stop|restart}"
        exit 1

esac

exit 0
